[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# If you want to use Next.js' Image optimization features with Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
